 global:
   scrape_interval: 15s # Scrape metrics every 15 seconds

 scrape_configs:
   - job_name: 'otel-collector' # Name of the job for scraping our app
     scrape_interval: 5s # Scrape metrics every 15 seconds
     static_configs:
       - targets: ['localhost:8889'] # Target to scrape (our app)
      #  - targets: ['host.docker.internal:4000'] # Target to scrape (our app)
 rule_files:
   - './alertmanager/alert.rules.yml'