 global:
   resolve_timeout: 5m # Alerts are considered resolved after 5 minutes of no new alerts

 route:
   group_by: ['job'] # Group alerts by job name
   group_wait: 30s # Wait 30 seconds to group alerts
   group_interval: 5m # Group alerts every 5 minutes
   repeat_interval: 12h # Repeat alerts every 12 hours
   receiver: 'email' # Send alerts to the email receiver

 receivers:
   - name: 'email'
     email_configs:
       - to: 'your-email@example.com' # Your email address
         from: 'alertmanager@example.com' # Sender email
         smarthost: 'smtp.example.com:587' # SMTP server (replace with your settings)
         auth_username: 'alertmanager' # SMTP username
         auth_password: 'password' # SMTP password